version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: "Django"
        versions:
          - ">= 4.0"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
