services:
  web:
    build: .
    command: tail -f /dev/null
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres_user:postgres_password@postgres:5432/postgres_db
      DJANGO_SETTINGS_MODULE: django3_template.settings.dev
      DJANGO_ENV: development
    env_file: .env
    volumes:
      - .:/app
    init: true
    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
