services:
  web:
    build: .
    command: tail -f /dev/null
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/app
    init: true
    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    # Make sure Postgres version is in sync with CI configs and is available on Heroku
    # https://devcenter.heroku.com/articles/heroku-postgres-version-support
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres_user", "-d", "postgres_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
