services:
  web:
    build: .
    command: tail -f /dev/null
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres_user:postgres_password@postgres:5432/postgres_db  # pragma: allowlist secret
      DJANGO_SETTINGS_MODULE: django_template.settings.dev
    volumes:
      - .:/app
    init: true
    stdin_open: true
    tty: true

  postgres:
    # Make sure Postgres version is in sync with CI configs and is available on Heroku
    # https://devcenter.heroku.com/articles/heroku-postgres-version-support
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
