name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    concurrency:
      group: tests-${{ github.head_ref || github.ref }}
      cancel-in-progress: true

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres # pragma: allowlist secret
      REDIS_URL: redis://localhost:6379/0 # pragma: allowlist secret
      SECRET_KEY: test # pragma: allowlist secret

    services:
      postgres:
        image: pgvector/pgvector:pg17
        env:
          POSTGRES_PASSWORD: postgres # pragma: allowlist secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"
      redis:
        image: redis:7.2
        ports:
          - "6379:6379"

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: "2.4.1"
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        uses: actions/cache@v5
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies with Poetry
        run: poetry install --no-interaction

      - name: Cache pre-commit environments
        uses: actions/cache@v5
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      # pyright-python can be a little flaky when it's instructed to check
      # files directly after it's first installed on GitHub Actions runners.
      #
      # Issues on GitHub seem to assert that it may have to do with
      # pyright-python trying to perform type-checking at the same time as
      # setting up node and npm for the first time.
      #
      # This command will set up node, npm, and pyright, so when it's run by
      # pre-commit, pyright will have already been fully set up.
      #
      # https://github.com/RobertCraigie/pyright-python/issues/200
      # https://github.com/RobertCraigie/pyright-python/issues/213
      # https://github.com/RobertCraigie/pyright-python/issues/231
      - name: Initialize pyright
        run: poetry run pyright --version

      - name: Run pre-commit hooks
        run: poetry run pre-commit run --show-diff-on-failure --color=always --all-files

      - name: Check for missing migrations
        run: poetry run python3 manage.py makemigrations --check --noinput
        if: always()

      - name: Collect staticfiles
        run: poetry run python3 manage.py collectstatic --noinput

      - name: Run tests
        run: poetry run python3 manage.py test --settings=django_template.settings.test -v=2

      - name: Build dev Docker image
        run: docker build -t django-template:dev --target dev .

      - name: Build production Docker image
        run: docker build -t django-template:production --target production .
